import random
from textwrap import dedent

CONTEXTS = [
"rooftop product launch at golden hour",
"glass-walled boardroom handshake",
"stand-up meeting around whiteboard sketches",
"open-plan startup hub with laptop huddle",
"coffee-bar pitch between cofounders",
"after-deal celebration with city skyline",
"warehouse walk-through with hardhats",
"design sprint sticky-note wall",
"VR demo in innovation lab",
"coding jam in co-working loft",
"mentor–mentee coaching session",
"customer success call in lounge",
"team high-five near elevator bank",
"remote standup on terrace",
"rainy-day umbrella networking",
"airport gate business meetup",
"hotel lobby investor chat",
"taxi curbside quick huddle",
"trade show booth product demo",
"expo stage lightning talk",
"podcast studio recording session",
"executive offsite fireside chat",
"team retreat in forest lodge",
"strategy sketch over brunch",
"sunrise jog-and-plan session",
"beachside offsite whiteboard",
"mountain summit team victory",
"cliffside hiking strategy chat",
"lakeside dock brainstorming",
"sailing teamwork adjusting lines",
"water-ski victory moment",
"kayak duo planning on shore",
"desert trailhead pep talk",
"snowy peak leadership pose",
"urban rooftop yoga debrief",
"city alley fashion-forward shoot",
"neon-lit night market pitch",
"startup bus-ride ideation",
"metro platform chance meeting",
"museum atrium investor intro",
"university lab partnership tour",
"prototype demo in makerspace",
"3D printer reveal in studio",
"robotics test bench discussion",
"AR overlay warehouse planning",
"drone field test coordination",
"solar farm site walkthrough",
"wind farm blade inspection",
"factory floor lean review",
"QA lab clipboard discussion",
"biotech cleanroom corridor chat",
"medical device design review",
"architects over city model",
"construction site plan check",
"crane overlook project briefing",
"real estate penthouse viewing",
"broker deal on balcony",
"retail pop-up launch day",
"street food cart partnership",
"artisan workshop collab talk",
"film set behind-the-scenes brief",
"photo studio creative kickoff",
"fashion showroom buyer meeting",
"music venue sponsor talk",
"sports arena suite sponsorship",
"charity gala donor circle",
"university career fair booth",
"campus quad startup recruiting",
"hackathon midnight sprint",
"code review wall monitor",
"cybersecurity war room huddle",
"data viz wall standup",
"ops center live dashboards",
"call center morale boost",
"logistics dock load planning",
"fleet yard dispatch sync",
"harbor crane logistics review",
"airport cargo operations brief",
"farm-to-table supply chat",
"vineyard patio strategy glass",
"brewery taproom partner cheers",
"restaurant kitchen pass briefing",
"food lab flavor testing",
"fitness studio brand collab",
"wellness retreat team circle",
"medical conference poster session",
"healthtech demo day",
"edtech classroom pilot",
"kids makerspace sponsorship talk",
"gaming lounge esports partnership",
"startup accelerator pitch bay",
"angel syndicate living-room pitch",
"VC office due diligence",
"law firm conference strategy",
"accounting team quarter-close",
"government lobby policy chat",
"town hall Q&A wrap-up",
"press conference green room",
"media interview street-side",
"rooftop drone shot wrap",
"night skyline closing deal",
"sunset boardwalk partnership",
"coastal cliff pep talk",
"forest overlook launch vows",
"rain-washed street win pose",
"snowfall city optimism walk"
]

STYLES = [
"neo-noir contrast",
"pastel vaporwave glow",
"cinematic teal-and-orange",
"golden hour warmth",
"high-key airy minimalism",
"low-key dramatic chiaroscuro",
"bokeh-rich lens aesthetic",
"anamorphic flare streaks",
"polaroid retro grain",
"35mm film grain realism",
"kodachrome nostalgia",
"matte muted palette",
"deep saturated primaries",
"soft desaturated modern",
"cool monochrome steel",
"warm monochrome sepia",
"duotone editorial finish",
"triadic color pop",
"split-tone cinematic",
"high dynamic range feel",
"soft bloom highlights",
"crisp hyperreal clarity",
"selective focus macro-feel",
"tilt-shift miniaturization",
"long-exposure light trails",
"motion blur dynamism",
"rain-kissed reflective streets",
"neon cyberpunk accents",
"futurist minimal brutalism",
"postmodern Memphis hints",
"art deco luxe geometric",
"bauhaus clean grids",
"brutalist concrete mood",
"organic biophilic textures",
"hand-painted watercolor wash",
"ink sketch overlay",
"charcoal sketch edges",
"collage magazine cutout",
"paper-tear texture",
"matisse cutout vibe",
"pop-art halftone dots",
"screenprint roughness",
"risograph misregister charm",
"glitch datamosh accents",
"CRT scanline nostalgia",
"holographic iridescence",
"pearlescent gentle sheen",
"oil paint impasto feel",
"pastel chalky softness",
"airbrush 80s poster",
"sci-fi hologram UI",
"AR HUD subtle overlay",
"isometric tech diagram hints",
"blueprint linework accents",
"architectural lineart",
"geometric gradients",
"mesh gradient modern",
"glassmorphism layers",
"frosted translucency",
"claymation soft forms",
"toy-camera vignetting",
"vintage lens swirls",
"lensbaby dreamy edges",
"retro-futurism optimism",
"y2k chrome shine",
"noir rain-slick city",
"sun-drenched coastal",
"overcast moody softness",
"desert sun haze",
"alpine crisp clarity",
"forest green lushness",
"nautical navy whites",
"industrial steel orange",
"earth-tone editorial",
"pastel tech minimal",
"bold posterized blocks",
"monochrome with accent color",
"gradient sky drama",
"backlit rim lighting",
"silhouette hero framing",
"low-angle power shot",
"wide-angle epic scale",
"medium shot intimacy",
"over-shoulder narrative",
"aerial drone sweep",
"gimbal smooth tracking feel",
"handheld documentary grit",
"studio key-fill-rim balance",
"practical practical-lights warmth",
"prismatic diffraction sparkle",
"starburst highlight points",
"soft haze atmosphere",
"god-ray volumetric light",
"rain mist texture",
"snow sparkle clarity",
"fog bank mystery",
"dappled leaf light",
"window light chiaroscuro",
"reflective glass layers",
"double-exposure blend",
"film burn edges",
"light leak nostalgia",
"color gel accents",
"split lighting portraiture"
]

RANDOMIZATION = [
"wide-angle 24mm perspective",
"standard 35–50mm human-eye view",
"telephoto 85–135mm compression",
"ultra-wide 16mm heroic scale",
"low-angle power composition",
"high-angle overview",
"eye-level candid framing",
"rule-of-thirds subject placement",
"central symmetrical balance",
"leading lines to subject",
"foreground object depth",
"frame-within-a-frame",
"reflections as framing",
"negative space top third",
"negative space left flank",
"negative space right flank",
"shallow depth f/1.8",
"deep focus f/11",
"backlight rim glow",
"side light sculpting",
"soft overcast fill",
"hard sunlight contrast",
"golden hour long shadows",
"blue hour cool ambience",
"night city neon",
"rain-wet streets sheen",
"mist/haze atmospheric depth",
"snowfall gentle motion",
"wind-swept hair/clothes",
"confetti micro-celebration",
"sparklers tiny celebration",
"balloons subtle party",
"papers in mid-air",
"laptop lid glow",
"phone screen keylight",
"sticky-notes color spray",
"glass reflections layers",
"doorway threshold framing",
"elevator chrome reflections",
"moving crowds motion blur",
"cars light trails",
"drone slight parallax",
"handheld documentary shake",
"tripod perfect stability",
"subject trio composition",
"duo partnership focus",
"solo hero founder",
"group of five energy",
"diverse age mix",
"gender-balanced cast",
"smart-casual wardrobe",
"formal suits sharp",
"outdoor athleisure mix",
"hardhat and vests",
"sailing technical gear",
"winter parkas alpine",
"rain jackets urban",
"sunglasses stylish touch",
"watches subtle luxury",
"minimal props clean",
"tech props tasteful",
"notebooks and pens",
"coffee cups convivial",
"whiteboard markers bold",
"posters on brick wall",
"neon signs hint",
"city skyline backdrop",
"harbor cranes backdrop",
"mountain ridge backdrop",
"forest canopy backdrop",
"desert dunes backdrop",
"coastal cliffs backdrop",
"lake mirror backdrop",
"snowy city backdrop",
"glass atrium backdrop",
"industrial loft backdrop",
"wood-and-plant office",
"black-and-steel office",
"color-accent startup office",
"retro mid-century lounge",
"scandinavian minimal space",
"japanese wabi-sabi calm",
"mediterranean light stone",
"latin urban vibrancy",
"african textile accents",
"indian jewel-tone hints",
"middle-eastern geometric tile",
"european old-town alley",
"australian coastal vibe",
"time-of-day sunrise",
"time-of-day midday",
"time-of-day sunset",
"time-of-day night",
"weather clear sky",
"weather scattered clouds",
"weather dramatic storm edge",
"season spring blossoms",
"season summer lush",
"season autumn leaves",
"season winter crisp",
"color palette warm bias",
"color palette cool bias",
"color palette balanced",
"contrast high",
"contrast medium",
"contrast low"
]


GUIDANCE_TEMPLATE = dedent("""\
Task: Turn the following business quote into a single compelling BACKGROUND IMAGE prompt for a viral quote card.

QUOTE: "{quote}"

Requirements:
- Audience: business leaders, founders, sales/ops/marketing pros.
- Purpose: background image behind the quote (do NOT include any text in the image).
- Primary context: {context_choice}
- Dominant style/aesthetic: {style_choices_str}
- Randomization emphasis this run: {randomization_choices_str}
- People: diverse, super attractive people, confident, happy, stylish, fashionable, but realistic.
- Composition: reserve clean negative space (preferably the top third) with soft background/bokeh for text overlay; avoid busy patterns behind text area.
- Lighting & color: natural or stylized lighting per the selected style; keep vibrant-yet-readable background behind future text.
- Camera & framing: choose lens/angle that supports drama and readability; ensure subjects aren’t cropped; leave breathing room for overlaid quote text.
- Safety/brand: no visible logos/brands, no famous landmarks implying endorsement, no risky behavior beyond normal outdoor activities, no politics/medical themes.
- Aspect ratio suggestion: {aspect_ratio}

Output format:
Return ONLY the final image prompt text, followed by a "Negative prompt:" line.

Structure exactly like this:
[Main descriptive prompt capturing the chosen scene, people, mood, lighting, lens, composition, and negative space for text overlay. Finish with aspect ratio instruction.]
ALWAYS include the following negative prompt:
Negative prompt: text, captions, subtitles, watermarks, logos, brand names, nudity, violence, gore, weapons, unsafe stunts, low quality, over-sharpening, extra fingers, distorted faces, deformed hands, duplicate people, heavy JPEG artifacts, individual pictures of males
""")

def build_image_prompt_instructions(
    quote: str,
    contexts=CONTEXTS,
    styles=STYLES,
    randomization=RANDOMIZATION,
    n_styles=(2,3),
    n_randomization=(5,8),
    seed: int | None = None
) -> str:
    """
    Create the instruction block you send to your LLM.
    The LLM then outputs the final [Main prompt ...] + Negative prompt: ...
    """
    if seed is not None:
        random.seed(seed)

    context_choice = random.choice(contexts)
    style_count = random.randint(*n_styles)
    rand_count = random.randint(*n_randomization)

    style_choices = random.sample(styles, style_count)
    randomization_choices = random.sample(randomization, rand_count)

    style_choices_str = ", ".join(style_choices)
    randomization_choices_str = ", ".join(randomization_choices)
    aspect_ratio = "1:1"

    return GUIDANCE_TEMPLATE.format(
        quote=quote.replace('"', '\\"'),
        context_choice=context_choice,
        style_choices_str=style_choices_str,
        randomization_choices_str=randomization_choices_str,
        aspect_ratio=aspect_ratio
    )

# --- Example usage ---
if __name__ == "__main__":
    quote = "Success is the sum of small efforts repeated day in and day out."
    instructions = build_image_prompt_instructions(quote, seed=42)
    print(instructions)
    # Send `instructions` to your LLM. Its response becomes the final image prompt for your generator.
